const data = [
  {
    id: '1',
    subtitle: 'Сказочное заморское яство',
    subtitleAlt: 'Котэ не одобряет?',
    title: 'Нямушка',
    ingredients: 'с фуа-гра',
    portionAmount: '10',
    portionText: 'порций',
    giftAmount: '',
    giftText: 'мышь в подарок',
    slogan: '',
    quantity: '0,5',
    unit: 'кг',
    image: 'cat.png',
    isInStock: true,
    isSelected: false,
    bannerText: {
      isNotSelected: 'Чего сидишь? Порадуй котэ, ',
      isSelected: 'Печень утки разварная с артишоками',
      notInStock: 'Печалька, с фуа-гра закончился',
    },
  },
  {
    id: '2',
    subtitle: 'Сказочное заморское яство',
    subtitleAlt: 'Котэ не одобряет?',
    title: 'Нямушка',
    ingredients: 'с рыбой',
    portionAmount: '40',
    portionText: 'порций',
    giftAmount: '2',
    giftText: 'мыши в подарок',
    slogan: '',
    quantity: '2',
    unit: 'кг',
    image: 'cat.png',
    isInStock: true,
    isSelected: false,
    bannerText: {
      isNotSelected: 'Чего сидишь? Порадуй котэ, ',
      isSelected: 'Головы щучьи с чесноком да свежайшая семгушка',
      notInStock: 'Печалька, с рыбой закончился',
    },
  },
  {
    id: '3',
    subtitle: 'Сказочное заморское яство',
    subtitleAlt: 'Котэ не одобряет?',
    title: 'Нямушка',
    ingredients: 'с курой',
    portionAmount: '100',
    portionText: 'порций',
    giftAmount: '5',
    giftText: 'мышей в подарок',
    slogan: 'заказчик доволен',
    quantity: '5',
    unit: 'кг',
    image: 'cat.png',
    isInStock: false,
    isSelected: false,
    bannerText: {
      isNotSelected: 'Чего сидишь? Порадуй котэ, ',
      isSelected: 'Филе из цыплят с трюфелями в бульоне',
      notInStock: 'Печалька, с курой закончился',
    },
  },
];

export default data;
